"""Second migration

Revision ID: 18142cd49c4e
Revises: 87535ea89441
Create Date: 2024-09-15 19:54:34.807300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18142cd49c4e'
down_revision: Union[str, None] = '87535ea89441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_task_per_day', 'tasks', ['user_id', 'created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_task_per_day', 'tasks', type_='unique')
    # ### end Alembic commands ###
